### ISSUE TITLE
Spring/BooPHF not compilable on windows

### ISSUE THREAD

**Issue by MueFab** [mitogen/genie#20]
**Describe the bug**
Spring does not compile on windows, as BooPHF (used by spring) includes the headers <sys/time.h> and <unistd.h>. These are not available on windows.

**To Reproduce**
1. Create an MSVC project file with cmake on windows using the repository.
2. Try to build it.

**Expected behavior**
The build should finish without errors.

**Environment (please complete the following information):**
 - OS: Windows
 - OS version: 10
 - Compiler: Visual Studio 16 2019
 - Compiler version: MSVC 19.26.28806.0

**Additional context**
https://dev.azure.com/janvoges/genie/_build/results?buildId=26&view=logs&j=022b0a5d-2698-5f72-7610-a845972a8b4c&t=bac7496d-7f04-5fb1-d241-7b8ca9cb3088

**Comment by shubhamchandak94** [comment]
Hi Fabian,
I looked into this:
- sys/time.h - I removed the dependency. It was only used for a progress bar, which we were not using anyway. (see feature/paired-end branch commit [here](https://github.com/mitogen/genie/commit/93f4713325ebb563d0e509dcbeae21aa4b00e3dd)
- unistd.h - I tried to remove the header and there were errors due to two functions: unlink and getpid. unlink is supposed to delete a file, and getpid is related to threading. I think both are available for windows (as aliases to _unlink and _getpid - see [this](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-getpid?view=vs-2019) and [this](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/unlink?view=vs-2019)). So it should be possible to fix this by including appropriate header guards. Since I don't have access to or experience with windows compilation, it will be great if someone more familiar can try to fix this. Otherwise I can try that.
Regards,
Shubham

**Comment by MueFab** [comment]
Hi Shubham,

removing the progress bar was already enough. Surprisingly, getpid and unlink are not an issue and recognized by MSVC. However, there are additional issues. The data type __uint128_t and the atomic functions __sync_fetch_and_or and __sync_fetch_and_and seem to be gcc extensions and not available in the Microsoft toolchain. Do you think it is possible to replace them?

**Comment by shubhamchandak94** [comment]
__sync_fetch_and_or -> [_InterlockerOr](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockedor-intrinsic-functions?view=vs-2019)
__sync_fetch_and_and -> [_InterlockedAnd](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockedand-intrinsic-functions?view=vs-2019)
__sync_fetch_and_add -> [_InterlockedAdd](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockedadd-intrinsic-functions?view=vs-2019)

uint64_t in fastrange64 function - see https://github.com/lemire/fastrange/blob/master/fastrange.h#L37 where they have a windows version

One place where the _sync replacements above might not work is for `int tid =  __sync_fetch_and_add (&_nb_living, 1);`, since the Windows version expects uint64_t, but I think it's easily fixable by changing the type of _nb_living to uint64.

Note: most of this is based on Google search and not on a deep understanding of their code. So we should make sure to test multithreading on Windows so that things work as expected.

**Comment by voges** [comment]
Genie now builds on Windows. Thanks go to @MueFab and @shubhamchandak94 !
